name: Android Web3Wallet deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
    # tags:
    #   - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:
    runs-on: macos-latest-xlarge

    steps:
    # Checkout the repo
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Create temp firebase key
    # - name: Create temp firebase key
    #   env:
    #     FIREBASE_KEY_BASE64: ${{ secrets.FIREBASE_KEY_BASE64 }}
    #   run: |
    #     # create variables
    #     FIREBASE_KEY_PATH=$RUNNER_TEMP/flutter-c7c2c-6df892fe6ddb.json

    #     # import certificate and provisioning profile from secrets
    #     echo -n "$FIREBASE_KEY_BASE64" | base64 --decode -o $FIREBASE_KEY_PATH

    # Install Java 17
    - name: Install Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
        architecture: x86_64
        cache: 'gradle'

    # Cache Gradle
    - name: Cache Gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    # # Install Fastlane
    # - name: Install Fastlane
    #   run: gem install fastlane
    
    # Install Flutter and Dependencies
    - uses: ./.github/actions/dependencies
    
    # Fastlane
    - name: Fastlane
      working-directory: example/wallet/android
      env:
        PROJECT_ID: ${{ secrets.WALLET_PROJECT_ID }}
        SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_WALLET_ID: ${{ secrets.FIREBASE_WALLET_ID }}
      run: |
        PUBSPEC_FILE=../../../pubspec.yaml
        FILE_VALUE=$(echo | grep "^version: " $PUBSPEC_FILE)
        PARTS=(${FILE_VALUE//:/ })
        FULL_VERSION=${PARTS[1]}
        VERSION_NUMBER=(${FULL_VERSION//-/ })

        fastlane add_plugin firebase_app_distribution
        fastlane release_firebase project_id:$PROJECT_ID app_version:$VERSION_NUMBER

# Launch locally
# act -j build --container-architecture linux/amd64 -P macos-latest-xlarge=-self-hosted --secret-file .github/workflows/.env.secret -W .github/workflows/release_wallet_android.yml
